services:
  - type: worker
    name: drh-casino-bot
    env: python
    buildCommand: "pip install aiogram==2.25.1 supabase==2.3.0 httpx==0.27.2"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.10

